apiVersion: apps/v1
kind: Deployment
metadata:
  name: councourse-test-nginx-deployment
spec:
  selector:
    matchLabels:
      app: councourse-test-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: councourse-test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
